# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "98bff288407bd9b18c4f138ff617c15c"
name = "new-test-app"
application_url = "https://filling-snowboard-optimize-choir.trycloudflare.com"
embedded = true
handle = "new-test-app-204"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers"

[auth]
redirect_urls = ["https://filling-snowboard-optimize-choir.trycloudflare.com/auth/callback", "https://filling-snowboard-optimize-choir.trycloudflare.com/auth/shopify/callback", "https://filling-snowboard-optimize-choir.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
